# PyNMR Config file, YAML
---
settings:
    probe_ip: 129.57.36.81
    meter_ip: 129.57.37.92
    siggen_ip: 129.57.37.91
    lockin_ip: 129.57.37.101
    labjack_ip: 129.57.37.97
    temp_scan_wait: 0.05         # seconds between temp change and read