# PyMEOP Config file, YAML
---
settings:
    probe_ip: 129.57.36.81
    meter_ip: 129.57.37.92
    siggen_ip: 129.57.37.91
    lockin_ip: 129.57.37.101
    labjack_ip: 129.57.37.97
    temp_scan_wait: 0.01         # seconds between temp change and read
    curr_scan_wait: 0.01         # seconds between curr change and read
    event_dir: 'data'
    log_dir: 'log'